apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers: 
  - image: test
    name: nginx
    volumeMounts:
      - name: config
        mountPath: /usr/share/nginx/html
        subPath: html
      - name: config
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: test-nfs-claim