apiVersion: v1
kind: Pod
metadata:
  name: nginx-preffered
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - hdd          
  containers:
  - name: nginx-preffered
    image: nginx
    imagePullPolicy: IfNotPresent
